cities = ['Brainerd', 'Nimrod', 'Baxter', 'Breezy Point', 'Crosslake', 'Merrifield', 'Crosby', 'Deerwood', 'Nisswa', 'Pequot Lakes', 'Pilliger', 'Pine River', 'Fort Ripley', 'Little Falls']
title = []
make = ['Kawaskaki', 'Sea-Doo', 'Yamaha']
model = ['Jet Ski', 'Spark', 'GTI 90', 'WaveRunner']


vehicleExamples = [
        {
                title: 'Sport Boat',
                type: 'Runabout',
                make: 'Carver',
                model: 'Sport',
                year: '2019',
                length: 20,
                capacity: 6,
                horsepower: 200,
                street: '1234 Prime Street',
                city: 'Aitkin',
                state: 'MN',
                zip: '54631',
                description: 'Great boat for the family. Teach the kids to ski this summer!',
                cabins: 0,
                heads: 0,
                dailyRate: 300,
                features: [],
        },
        {
                title: 'Great Family Boat',
                type: 'Runabout',
                make: 'Carver',
                model: 'Runner',
                year: '2019',
                length: 20,
                capacity: 6,
                horsepower: 200,
                street: '16973 Blakeman Road',
                city: 'Brainerd',
                state: 'MN',
                zip: '56401',
                description: 'Great boat for the family. Teach the kids to ski this summer! Explore the lakes',
                cabins: 0,
                heads: 0,
                dailyRate: 300,
                features: [],
        },
        {
                title: 'Fun Summer boat to explore the lake',
                type: 'Runabout',
                make: 'Sea Ray',
                model: 'LX240',
                year: '2018',
                length: 24,
                capacity: 10,
                horsepower: 200,
                street: '19135 Spencer Rd',
                city: 'Baxter',
                state: 'MN',
                zip: '56401',
                description: 'Explore the big lakes all while you are at the cabin',
                cabins: 0,
                heads: 0,
                dailyRate: 300,
                features: [],
        },
        {
                title: 'Fun Summer boat to explore the lake',
                type: 'Runabout',
                make: 'Forwins',
                model: 'Cruiser',
                year: '2020',
                length: 18,
                capacity: 10,
                horsepower: 150,
                street: '9522 Northgate Ln',
                city: 'Brainerd',
                state: 'MN',
                zip: '56401',
                description: 'You and the kids will make great memories exploring the waters around Long Lake',
                cabins: 0,
                heads: 0,
                dailyRate: 300,
                features: [],
        },
]


