cities = ['Brainerd', 'Nimrod', 'Baxter', 'Breezy Point', 'Crosslake', 'Merrifield', 'Crosby', 'Deerwood', 'Nisswa', 'Pequot Lakes', 'Pilliger', 'Pine River', 'Fort Ripley', 'Little Falls']
title = []
make = ['Kawaskaki', 'Sea-Doo', 'Yamaha']
model = ['Jet Ski', 'Spark', 'GTI 90', 'WaveRunner']


vehicleExamples = [
        {
                title: 'Sport Boat',
                type: 'Runabout',
                make: 'Carver',
                model: 'Sport',
                year: '2019',
                length: 20,
                capacity: 6,
                horsepower: 200,
                street: '1234 Prime Street',
                city: 'Aitkin',
                state: 'MN',
                zip: '54631',
                description: 'Great boat for the family. Teach the kids to ski this summer!',
                cabins: 0,
                heads: 0,
                dailyRate: 550,
                features: [],
        },
        {
                title: 'Great Family Boat',
                type: 'Runabout',
                make: 'Carver',
                model: 'Runner',
                year: '2019',
                length: 20,
                capacity: 6,
                horsepower: 200,
                street: '16973 Blakeman Road',
                city: 'Brainerd',
                state: 'MN',
                zip: '56401',
                description: 'Great boat for the family. Teach the kids to ski this summer! Explore the lakes',
                cabins: 0,
                heads: 0,
                dailyRate: 350,
                features: [],
        },
        {
                title: 'Fun Summer boat to explore the lake',
                type: 'Runabout',
                make: 'Sea Ray',
                model: 'LX240',
                year: '2018',
                length: 24,
                capacity: 10,
                horsepower: 200,
                street: '19135 Spencer Rd',
                city: 'Baxter',
                state: 'MN',
                zip: '56401',
                description: 'Explore the big lakes all while you are at the cabin',
                cabins: 0,
                heads: 0,
                dailyRate: 300,
                features: [],
        },
        {
                title: 'Fun Summer boat to explore the lake',
                type: 'Runabout',
                make: 'Forwins',
                model: 'Cruiser',
                year: '2020',
                length: 18,
                capacity: 10,
                horsepower: 150,
                street: '9522 Northgate Ln',
                city: 'Brainerd',
                state: 'MN',
                zip: '56401',
                description: 'You and the kids will make great memories exploring the waters around Long Lake',
                cabins: 0,
                heads: 0,
                dailyRate: 400,
                features: [],
        },
        {
                title: 'Fast Nitro Sport Series fishing boat. Get to the hot spots fast! Open deck, 200hp, fish finder, trolling motor',
                type: 'Fishing',
                make: 'Nitro',
                model: 'Sport X',
                year: '2020',
                length: 19,
                capacity: 4,
                horsepower: 200,
                street: '22267 Buckhorn Trail',
                city: 'Merrifield',
                state: 'MN',
                zip: '56465',
                description: 'Bring a guide out on Spider Lake and fish like a pro',
                cabins: 0,
                heads: 0,
                dailyRate: 275,
                features: [],
        },
        {
                title: 'Z Series Nitro! FAST!! Fly across the lake to the next spot!',
                type: 'Fishing',
                make: 'Nitro',
                model: 'Z Series',
                year: '2020',
                length: 20,
                capacity: 4,
                horsepower: 220,
                street: '23048 Antler Rd',
                city: 'Crosby',
                state: 'MN',
                zip: '56441',
                description: 'Buckle up and wear a PFD this boat flies!',
                cabins: 0,
                heads: 0,
                dailyRate: 350,
                features: [],
        },
        {
                title: 'Multi Species Nitro Boat, Deep Hull, great for big choppy water!',
                type: 'Fishing',
                make: 'Nitro',
                model: 'Multi Species',
                year: '2018',
                length: 17,
                capacity: 4,
                horsepower: 220,
                street: '23744 Clover Dr',
                city: 'Merrifield',
                state: 'MN',
                zip: '56465',
                description: 'Great boat that fits 4 adults comfortable, great fishing from any side of the boat!',
                cabins: 0,
                heads: 0,
                dailyRate: 200,
                features: [],
        },
        {
                title: 'Alumicraft Fishing Boat for the whole family!',
                type: 'Fishing',
                make: 'Alumacraft',
                model: 'Striker',
                year: '2017',
                length: 17,
                capacity: 4,
                horsepower: 175,
                street: '12235 Lakeview Ln',
                city: 'Merrifield',
                state: 'MN',
                zip: '56465',
                description: 'Easy to operate fishing boat, comfortable great for getting the big ones!',
                cabins: 0,
                heads: 0,
                dailyRate: 190,
                features: [],
        },
]


